#include <sys/types.h>
#include "syntax.h"
int pacc_wrap(
    __attribute__((unused)) const char *ign0,
    __attribute__((unused)) char *ign1,
    __attribute__((unused)) size_t ign2,
    struct s_node **result) {
struct s_node *n, *p0, *p1, *p2, *p3, *p4, *p5, *p6, *p7;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "*"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = s_kid(rule, p2); n->text = "Star"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = s_new(lit); n->text = "|"; p5 = n;
n = s_kid(seq, p5); p4 = n;
n = s_new(lit); n->text = "/"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = cons(s_kid(alt, p4), p3); p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Slash"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "?"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Query"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "+"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Plus"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = ")"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "rParen"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "("; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "lParen"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "!"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Not"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = s_new(lit); n->text = "%"; p5 = n;
n = s_kid(seq, p5); p4 = n;
n = s_new(lit); n->text = "ε"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = cons(s_kid(alt, p4), p3); p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Epsilon"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "."; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Dot"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "$"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Dollar"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "::"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "ColCol"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = ":"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Colon"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "}"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "rBrace"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "{"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "lBrace"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = s_new(lit); n->text = "->"; p5 = n;
n = s_kid(seq, p5); p4 = n;
n = s_new(lit); n->text = "→"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = cons(s_kid(alt, p4), p3); p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "rArrow"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = s_new(lit); n->text = "="; p5 = n;
n = s_kid(seq, p5); p4 = n;
n = s_new(lit); n->text = "<-"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_new(lit); n->text = "←"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = cons(s_kid(alt, p4), p3); p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "lArrow"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "&"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "And"; p1 = n;
n = s_new(call); n->text = "Comment"; p6 = n;
n = s_kid(seq, p6); p5 = n;
n = s_new(cceq); n->number = 10; p7 = n;
n = cons(s_new(cceq), p7); n->number = 9; p7 = n;
n = cons(s_new(cceq), p7); n->number = 32; p7 = n;
n = s_kid(cclass, p7); n->text = " \\t\\n"; p6 = n;
n = cons(s_kid(seq, p6), p5); p5 = n;
n = s_kid(alt, p5); p4 = n;
n = s_kid(rep, p4); p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "_"; p1 = n;
n = s_new(lit); n->text = "*/"; p4 = n;
n = s_new(any); p6 = n;
n = s_new(lit); n->text = "*/"; p7 = n;
n = cons(s_kid(not, p7), p6); p6 = n;
n = s_kid(seq, p6); p5 = n;
n = cons(s_kid(rep, p5), p4); p4 = n;
n = cons(s_new(lit), p4); n->text = "/*"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(lit); n->text = "\\n"; p4 = n;
n = s_new(cceq); n->number = 10; p6 = n;
n = s_kid(cclass, p6); n->text = "^\\n"; p5 = n;
n = cons(s_kid(rep, p5), p4); p4 = n;
n = cons(s_new(lit), p4); n->text = "//"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "C_Comment"; p1 = n;
n = s_new(call); n->text = "C_Comment"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(lit); n->text = "\\n"; p4 = n;
n = s_new(cceq); n->number = 10; p6 = n;
n = s_kid(cclass, p6); n->text = "^\\n"; p5 = n;
n = cons(s_kid(rep, p5), p4); p4 = n;
n = cons(s_new(lit), p4); n->text = "#"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Comment"; p1 = n;
n = s_new(ccle); n->number = 102; p4 = n;
n = cons(s_new(ccge), p4); n->number = 97; p4 = n;
n = cons(s_new(ccle), p4); n->number = 70; p4 = n;
n = cons(s_new(ccge), p4); n->number = 65; p4 = n;
n = cons(s_new(ccle), p4); n->number = 57; p4 = n;
n = cons(s_new(ccge), p4); n->number = 48; p4 = n;
n = s_kid(cclass, p4); n->text = "0-9A-Fa-f"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "HexDigit"; p1 = n;
n = s_new(call); n->text = "HexDigit"; p3 = n;
n = cons(s_new(call), p3); n->text = "HexDigit"; p3 = n;
n = cons(s_new(call), p3); n->text = "HexDigit"; p3 = n;
n = cons(s_new(call), p3); n->text = "HexDigit"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "HexQuad"; p1 = n;
n = s_new(call); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "'"; p3 = n;
n = cons(s_new(call), p3); n->text = "QuotedChar"; p3 = n;
n = cons(s_new(lit), p3); n->text = "'"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CharLit"; p1 = n;
n = s_new(call); n->text = "HexQuad"; p5 = n;
n = cons(s_new(call), p5); n->text = "HexQuad"; p5 = n;
n = cons(s_new(lit), p5); n->text = "\\\\U"; p5 = n;
n = s_kid(seq, p5); p4 = n;
n = s_new(call); n->text = "HexQuad"; p5 = n;
n = cons(s_new(lit), p5); n->text = "\\\\u"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_kid(alt, p4); p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "UniversalEscape"; p1 = n;
n = s_new(call); n->text = "HexDigit"; p4 = n;
n = s_kid(rep, p4); n->text = ",1"; p3 = n;
n = cons(s_new(call), p3); n->text = "HexDigit"; p3 = n;
n = cons(s_new(lit), p3); n->text = "\\\\x"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "HexEscape"; p1 = n;
n = s_new(ccle); n->number = 55; p5 = n;
n = cons(s_new(ccge), p5); n->number = 48; p5 = n;
n = s_kid(cclass, p5); n->text = "0-7"; p4 = n;
n = s_kid(rep, p4); n->text = ",1"; p3 = n;
n = s_new(ccle); n->number = 55; p5 = n;
n = cons(s_new(ccge), p5); n->number = 48; p5 = n;
n = s_kid(cclass, p5); n->text = "0-7"; p4 = n;
n = cons(s_kid(rep, p4), p3); n->text = ",1"; p3 = n;
n = s_new(ccle); n->number = 55; p4 = n;
n = cons(s_new(ccge), p4); n->number = 48; p4 = n;
n = cons(s_kid(cclass, p4), p3); n->text = "0-7"; p3 = n;
n = cons(s_new(lit), p3); n->text = "\\\\"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "OctalEscape"; p1 = n;
n = s_new(lit); n->text = "\\?"; p5 = n;
n = s_kid(seq, p5); p4 = n;
n = s_new(lit); n->text = "\\\""; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_new(lit); n->text = "\\'"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_new(lit); n->text = "\\\\"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_new(lit); n->text = "v"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_new(lit); n->text = "t"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_new(lit); n->text = "r"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_new(lit); n->text = "n"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_new(lit); n->text = "f"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_new(lit); n->text = "b"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_new(lit); n->text = "a"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = s_kid(alt, p4); p3 = n;
n = cons(s_new(lit), p3); n->text = "\\\\"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "SimpleEscape"; p1 = n;
n = s_new(call); n->text = "UniversalEscape"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(call); n->text = "HexEscape"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(call); n->text = "OctalEscape"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(call); n->text = "SimpleEscape"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "void"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Escape"; p1 = n;
n = s_new(ident); n->text = "ref"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 145; n->pair[1] = 34; p4 = n;
n = s_kid(expr, p4); n->text = " ref() "; p3 = n;
n = s_new(cceq); n->number = 92; p6 = n;
n = s_kid(cclass, p6); n->text = "^\\\\"; p5 = n;
n = s_kid(seq, p5); p4 = n;
n = s_new(call); n->text = "Escape"; p5 = n;
n = cons(s_kid(seq, p5), p4); p4 = n;
n = cons(s_kid(alt, p4), p3); p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "ref_t"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "QuotedChar"; p1 = n;
n = s_new(ident); n->text = "ref"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 143; n->pair[1] = 45; p4 = n;
n = s_kid(expr, p4); n->text = " ref() "; p3 = n;
n = s_new(call); n->text = "QuotedChar"; p5 = n;
n = s_new(lit); n->text = "\\\""; p6 = n;
n = cons(s_kid(not, p6), p5); p5 = n;
n = s_kid(seq, p5); p4 = n;
n = cons(s_kid(rep, p4), p3); p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "ref_t"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "QuotedChars"; p1 = n;
n = s_new(ident); n->text = "q"; p4 = n;
n = cons(s_new(ident), p4); n->text = "ref_dup"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 141; n->pair[1] = 42; p4 = n;
n = s_kid(expr, p4); n->text = " ref_dup(q) "; p3 = n;
n = cons(s_new(call), p3); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "\\\""; p3 = n;
n = s_new(call); n->text = "QuotedChars"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "q"; p3 = n;
n = cons(s_new(lit), p3); n->text = "\\\""; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "char *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "StringLit"; p1 = n;
n = s_new(ident); n->text = "n"; p4 = n;
n = cons(s_new(ident), p4); n->text = "ref_dup"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 139; n->pair[1] = 24; p4 = n;
n = s_kid(expr, p4); n->text = " ref_dup(n) "; p3 = n;
n = cons(s_new(call), p3); n->text = "_"; p3 = n;
n = s_new(ccle); n->number = 57; p6 = n;
n = cons(s_new(ccge), p6); n->number = 48; p6 = n;
n = s_kid(cclass, p6); n->text = "0-9"; p5 = n;
n = s_kid(rep, p5); n->text = "1,"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "n"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "char *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Number"; p1 = n;
n = s_new(ident); n->text = "n"; p4 = n;
n = cons(s_new(ident), p4); n->text = "ref_dup"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 137; n->pair[1] = 49; p4 = n;
n = s_kid(expr, p4); n->text = " ref_dup(n) "; p3 = n;
n = cons(s_new(call), p3); n->text = "_"; p3 = n;
n = s_new(ccle); n->number = 57; p7 = n;
n = cons(s_new(ccge), p7); n->number = 48; p7 = n;
n = cons(s_new(ccle), p7); n->number = 122; p7 = n;
n = cons(s_new(ccge), p7); n->number = 97; p7 = n;
n = cons(s_new(ccle), p7); n->number = 90; p7 = n;
n = cons(s_new(ccge), p7); n->number = 65; p7 = n;
n = cons(s_new(cceq), p7); n->number = 95; p7 = n;
n = s_kid(cclass, p7); n->text = "_A-Za-z0-9"; p6 = n;
n = s_kid(rep, p6); p5 = n;
n = s_new(ccle); n->number = 122; p6 = n;
n = cons(s_new(ccge), p6); n->number = 97; p6 = n;
n = cons(s_new(ccle), p6); n->number = 90; p6 = n;
n = cons(s_new(ccge), p6); n->number = 65; p6 = n;
n = cons(s_new(cceq), p6); n->number = 95; p6 = n;
n = cons(s_kid(cclass, p6), p5); n->text = "_A-Za-z"; p5 = n;
n = s_kid(seq, p5); p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "n"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "char *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Name"; p1 = n;
n = s_new(ident); n->text = "preamble"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_text"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 135; n->pair[1] = 10; p5 = n;
n = s_kid(expr, p5); n->text = " s_text(preamble, 0) "; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "c"; p5 = n;
n = cons(s_new(ident), p5); n->text = "preamble"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_retype"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 134; n->pair[1] = 15; p5 = n;
n = s_kid(expr, p5); n->text = " s_retype(preamble, c) "; p4 = n;
n = s_new(call); n->text = "Code"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "c"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Preamble"; p1 = n;
n = s_new(coords); n->pair[0] = 123; n->pair[1] = 36; p5 = n;
n = s_kid(expr, p5); n->text = " \"*\" "; p4 = n;
n = cons(s_new(call), p4); n->text = "Star"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(call); n->text = "Name"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "char *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "TypeRaw"; p1 = n;
n = s_new(ident); n->text = "t"; p4 = n;
n = cons(s_new(ident), p4); n->text = "type"; p4 = n;
n = cons(s_new(ident), p4); n->text = "s_text"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 121; n->pair[1] = 28; p4 = n;
n = s_kid(expr, p4); n->text = " s_text(type, t) "; p3 = n;
n = s_new(call); n->text = "TypeRaw"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "t"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "TypeElement"; p1 = n;
n = s_new(call); n->text = "TypeElement"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "ts"; p5 = n;
n = cons(s_new(ident), p5); n->text = "t"; p5 = n;
n = cons(s_new(ident), p5); n->text = "append"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 118; n->pair[1] = 40; p5 = n;
n = s_kid(expr, p5); n->text = " append(t, ts) "; p4 = n;
n = s_new(call); n->text = "TypeElements"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "ts"; p4 = n;
n = s_new(call); n->text = "TypeElement"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "t"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "TypeElements"; p1 = n;
n = s_new(ident); n->text = "s_stashed_type"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 115; n->pair[1] = 10; p5 = n;
n = s_kid(expr, p5); n->text = " s_stashed_type() "; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "ts"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_stash_type"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 114; n->pair[1] = 33; p5 = n;
n = s_kid(expr, p5); n->text = " s_stash_type(ts) "; p4 = n;
n = s_new(call); n->text = "TypeElements"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "ts"; p4 = n;
n = cons(s_new(call), p4); n->text = "ColCol"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "char *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "TypeOptional"; p1 = n;
n = s_new(ident); n->text = "n"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 111; n->pair[1] = 36; p4 = n;
n = s_kid(expr, p4); n->text = "n"; p3 = n;
n = cons(s_new(call), p3); n->text = "rBrace"; p3 = n;
n = s_new(call); n->text = "CodeAndNames"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "n"; p3 = n;
n = cons(s_new(lit), p3); n->text = "{"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Code"; p1 = n;
n = s_new(ident); n->text = "n"; p4 = n;
n = cons(s_new(ident), p4); n->text = "pacc_coords"; p4 = n;
n = cons(s_new(ident), p4); n->text = "s_coords"; p4 = n;
n = cons(s_new(ident), p4); n->text = "cons"; p4 = n;
n = cons(s_new(ident), p4); n->text = "ref_str"; p4 = n;
n = cons(s_new(ident), p4); n->text = "expr"; p4 = n;
n = cons(s_new(ident), p4); n->text = "s_both"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 109; n->pair[1] = 3; p4 = n;
n = s_kid(expr, p4); n->text = " s_both(expr, ref_str(), cons(s_coords(pacc_coords), n)) "; p3 = n;
n = s_new(call); n->text = "CodeNames"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "n"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CodeAndNames"; p1 = n;
n = s_new(coords); n->pair[0] = 95; n->pair[1] = 10; p5 = n;
n = s_kid(expr, p5); n->text = " 0 "; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "ps"; p5 = n;
n = cons(s_new(ident), p5); n->text = "ns"; p5 = n;
n = cons(s_new(ident), p5); n->text = "append"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 94; n->pair[1] = 50; p5 = n;
n = s_kid(expr, p5); n->text = " append(ns, ps) "; p4 = n;
n = s_new(call); n->text = "CodeNames"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "ps"; p4 = n;
n = cons(s_new(call), p4); n->text = "rBrace"; p4 = n;
n = s_new(call); n->text = "CodeNames"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "ns"; p4 = n;
n = cons(s_new(call), p4); n->text = "lBrace"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "ns"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 93; n->pair[1] = 28; p5 = n;
n = s_kid(expr, p5); n->text = "ns"; p4 = n;
n = s_new(call); n->text = "CodeNames"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "ns"; p4 = n;
n = s_new(cceq); n->number = 125; p5 = n;
n = cons(s_new(cceq), p5); n->number = 123; p5 = n;
n = cons(s_kid(cclass, p5), p4); n->text = "^{}"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "ns"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 92; n->pair[1] = 32; p5 = n;
n = s_kid(expr, p5); n->text = "ns"; p4 = n;
n = s_new(call); n->text = "CodeNames"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "ns"; p4 = n;
n = cons(s_new(call), p4); n->text = "C_Comment"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "ns"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 91; n->pair[1] = 30; p5 = n;
n = s_kid(expr, p5); n->text = "ns"; p4 = n;
n = s_new(call); n->text = "CodeNames"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "ns"; p4 = n;
n = cons(s_new(call), p4); n->text = "CharLit"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "ns"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 90; n->pair[1] = 32; p5 = n;
n = s_kid(expr, p5); n->text = "ns"; p4 = n;
n = s_new(call); n->text = "CodeNames"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "ns"; p4 = n;
n = cons(s_new(call), p4); n->text = "StringLit"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "ns"; p5 = n;
n = cons(s_new(ident), p5); n->text = "n"; p5 = n;
n = cons(s_new(ident), p5); n->text = "ident"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_text"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_set_cons"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 89; n->pair[1] = 28; p5 = n;
n = s_kid(expr, p5); n->text = " s_set_cons(s_text(ident, n), ns) "; p4 = n;
n = s_new(call); n->text = "CodeNames"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "ns"; p4 = n;
n = s_new(call); n->text = "Name"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "n"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CodeNames"; p1 = n;
n = s_new(ident); n->text = "pacc_coords"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_coords"; p5 = n;
n = cons(s_new(ident), p5); n->text = "n"; p5 = n;
n = cons(s_new(ident), p5); n->text = "expr"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_both"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 86; n->pair[1] = 17; p5 = n;
n = s_kid(expr, p5); n->text = " s_both(expr, n, s_coords(pacc_coords)) "; p4 = n;
n = s_new(call); n->text = "Number"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "n"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "n"; p5 = n;
n = cons(s_new(ident), p5); n->text = "ident"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_text"; p5 = n;
n = cons(s_new(ident), p5); n->text = "pacc_coords"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_coords"; p5 = n;
n = cons(s_new(ident), p5); n->text = "cons"; p5 = n;
n = cons(s_new(ident), p5); n->text = "expr"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_both"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 85; n->pair[1] = 15; p5 = n;
n = s_kid(expr, p5); n->text = " s_both(expr, n, cons(s_coords(pacc_coords), s_text(ident, n))) "; p4 = n;
n = s_new(call); n->text = "Name"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "n"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "BareResult"; p1 = n;
n = s_new(ident); n->text = "c"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 82; n->pair[1] = 24; p5 = n;
n = s_kid(expr, p5); n->text = "c"; p4 = n;
n = s_new(call); n->text = "Code"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "c"; p4 = n;
n = s_new(call); n->text = "rArrow"; p5 = n;
n = cons(s_kid(rep, p5), p4); n->text = ",1"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "b"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 80; n->pair[1] = 29; p5 = n;
n = s_kid(expr, p5); n->text = "b"; p4 = n;
n = s_new(call); n->text = "BareResult"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "b"; p4 = n;
n = cons(s_new(call), p4); n->text = "rArrow"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Result"; p1 = n;
n = s_new(ident); n->text = "char"; p4 = n;
n = cons(s_new(ident), p4); n->text = "unsigned"; p4 = n;
n = cons(s_new(ident), p4); n->text = "const"; p4 = n;
n = cons(s_new(ident), p4); n->text = "s_ccnode"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 77; n->pair[1] = 19; p4 = n;
n = s_kid(expr, p4); n->text = " s_ccnode((const unsigned char *)\"]\") "; p3 = n;
n = cons(s_new(lit), p3); n->text = "]"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CCrBracket"; p1 = n;
n = s_new(ident); n->text = "char"; p4 = n;
n = cons(s_new(ident), p4); n->text = "unsigned"; p4 = n;
n = cons(s_new(ident), p4); n->text = "const"; p4 = n;
n = cons(s_new(ident), p4); n->text = "s_ccnode"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 75; n->pair[1] = 36; p4 = n;
n = s_kid(expr, p4); n->text = " s_ccnode((const unsigned char *)\"-\") "; p3 = n;
n = cons(s_new(lit), p3); n->text = "-"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CCHyphen"; p1 = n;
n = s_new(ident); n->text = "y"; p5 = n;
n = cons(s_new(ident), p5); n->text = "ref_dup"; p5 = n;
n = cons(s_new(ident), p5); n->text = "char"; p5 = n;
n = cons(s_new(ident), p5); n->text = "unsigned"; p5 = n;
n = cons(s_new(ident), p5); n->text = "const"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 73; n->pair[1] = 29; p5 = n;
n = s_kid(expr, p5); n->text = " (const unsigned char *)ref_dup(y) "; p4 = n;
n = s_new(call); n->text = "QuotedChar"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "y"; p4 = n;
n = s_new(lit); n->text = "]"; p5 = n;
n = cons(s_kid(not, p5), p4); p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "char"; p5 = n;
n = cons(s_new(ident), p5); n->text = "unsigned"; p5 = n;
n = cons(s_new(ident), p5); n->text = "const"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 72; n->pair[1] = 14; p5 = n;
n = s_kid(expr, p5); n->text = " (const unsigned char *)\"]\" "; p4 = n;
n = cons(s_new(lit), p4); n->text = "\\\\]"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "const unsigned char *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CCChar"; p1 = n;
n = s_new(ident); n->text = "c"; p4 = n;
n = cons(s_new(ident), p4); n->text = "s_ccnode"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 69; n->pair[1] = 20; p4 = n;
n = s_kid(expr, p4); n->text = " s_ccnode(c) "; p3 = n;
n = s_new(call); n->text = "CCChar"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "c"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CCNode"; p1 = n;
n = s_new(ident); n->text = "n"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 67; n->pair[1] = 23; p5 = n;
n = s_kid(expr, p5); n->text = "n"; p4 = n;
n = s_new(call); n->text = "CCNode"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "n"; p4 = n;
n = s_new(lit); n->text = "-"; p5 = n;
n = cons(s_kid(not, p5), p4); p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "b"; p5 = n;
n = cons(s_new(ident), p5); n->text = "a"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_ccrange"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 66; n->pair[1] = 29; p5 = n;
n = s_kid(expr, p5); n->text = " s_ccrange(a, b) "; p4 = n;
n = s_new(ident); n->text = "number"; p5 = n;
n = cons(s_new(ident), p5); n->text = "b"; p5 = n;
n = cons(s_new(ident), p5); n->text = "a"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 66; n->pair[1] = 31; p5 = n;
n = cons(s_kid(guard, p5), p4); n->text = " a->number < b->number "; p4 = n;
n = s_new(call); n->text = "CCNode"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "b"; p4 = n;
n = cons(s_new(lit), p4); n->text = "-"; p4 = n;
n = s_new(call); n->text = "CCNode"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "a"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CCRange"; p1 = n;
n = s_new(ident); n->text = "c"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 63; n->pair[1] = 19; p5 = n;
n = s_kid(expr, p5); n->text = "c"; p4 = n;
n = s_new(call); n->text = "CCRange"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "c"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "cs"; p5 = n;
n = cons(s_new(ident), p5); n->text = "c"; p5 = n;
n = cons(s_new(ident), p5); n->text = "append"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 62; n->pair[1] = 30; p5 = n;
n = s_kid(expr, p5); n->text = " append(c, cs) "; p4 = n;
n = s_new(call); n->text = "CCRanges"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "cs"; p4 = n;
n = s_new(call); n->text = "CCRange"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "c"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CCRanges"; p1 = n;
n = s_new(ident); n->text = "cs"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 59; n->pair[1] = 21; p5 = n;
n = s_kid(expr, p5); n->text = "cs"; p4 = n;
n = s_new(call); n->text = "CCRanges"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "cs"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "cs"; p5 = n;
n = cons(s_new(ident), p5); n->text = "c"; p5 = n;
n = cons(s_new(ident), p5); n->text = "append"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 58; n->pair[1] = 31; p5 = n;
n = s_kid(expr, p5); n->text = " append(c, cs) "; p4 = n;
n = s_new(call); n->text = "CCHyphen"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "c"; p4 = n;
n = s_new(call); n->text = "CCRanges"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "cs"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "cs"; p5 = n;
n = cons(s_new(ident), p5); n->text = "c"; p5 = n;
n = cons(s_new(ident), p5); n->text = "append"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 57; n->pair[1] = 34; p5 = n;
n = s_kid(expr, p5); n->text = " append(c, cs) "; p4 = n;
n = s_new(call); n->text = "CCRanges"; p6 = n;
n = s_kid(rep, p6); n->text = ",1"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "cs"; p4 = n;
n = s_new(call); n->text = "CCrBracket"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "c"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "cs"; p5 = n;
n = cons(s_new(ident), p5); n->text = "c"; p5 = n;
n = cons(s_new(ident), p5); n->text = "append"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 56; n->pair[1] = 32; p5 = n;
n = s_kid(expr, p5); n->text = " append(c, cs) "; p4 = n;
n = s_new(call); n->text = "CCRanges"; p6 = n;
n = s_kid(rep, p6); n->text = ",1"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "cs"; p4 = n;
n = s_new(call); n->text = "CCHyphen"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "c"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CClass2"; p1 = n;
n = s_new(ident); n->text = "c"; p4 = n;
n = cons(s_new(ident), p4); n->text = "ref_str"; p4 = n;
n = cons(s_new(ident), p4); n->text = "cclass"; p4 = n;
n = cons(s_new(ident), p4); n->text = "s_both"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 53; n->pair[1] = 29; p4 = n;
n = s_kid(expr, p4); n->text = " s_both(cclass, ref_str(), c) "; p3 = n;
n = s_new(call); n->text = "CClass2"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "c"; p3 = n;
n = s_new(lit); n->text = "^"; p4 = n;
n = cons(s_kid(rep, p4), p3); n->text = ",1"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CClass1"; p1 = n;
n = s_new(ident); n->text = "c"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 51; n->pair[1] = 33; p4 = n;
n = s_kid(expr, p4); n->text = "c"; p3 = n;
n = cons(s_new(call), p3); n->text = "_"; p3 = n;
n = cons(s_new(lit), p3); n->text = "]"; p3 = n;
n = s_new(call); n->text = "CClass1"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "c"; p3 = n;
n = cons(s_new(lit), p3); n->text = "["; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "CClass0"; p1 = n;
n = s_new(ident); n->text = "r"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 49; n->pair[1] = 31; p5 = n;
n = s_kid(expr, p5); n->text = "r"; p4 = n;
n = cons(s_new(call), p4); n->text = "rParen"; p4 = n;
n = s_new(call); n->text = "Rule0"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "r"; p4 = n;
n = cons(s_new(call), p4); n->text = "lParen"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "c"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 48; n->pair[1] = 19; p5 = n;
n = s_kid(expr, p5); n->text = "c"; p4 = n;
n = s_new(call); n->text = "CClass0"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "c"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "l"; p5 = n;
n = cons(s_new(ident), p5); n->text = "lit"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_text"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 47; n->pair[1] = 20; p5 = n;
n = s_kid(expr, p5); n->text = " s_text(lit, l) "; p4 = n;
n = s_new(call); n->text = "StringLit"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "l"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "any"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_new"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 46; n->pair[1] = 12; p5 = n;
n = s_kid(expr, p5); n->text = " s_new(any) "; p4 = n;
n = cons(s_new(call), p4); n->text = "Dot"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "n"; p5 = n;
n = cons(s_new(ident), p5); n->text = "call"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_text"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 45; n->pair[1] = 31; p5 = n;
n = s_kid(expr, p5); n->text = " s_text(call, n) "; p4 = n;
n = s_new(call); n->text = "ColCol"; p5 = n;
n = cons(s_kid(not, p5), p4); p4 = n;
n = s_new(call); n->text = "lArrow"; p5 = n;
n = cons(s_kid(not, p5), p4); p4 = n;
n = s_new(call); n->text = "Name"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "n"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Rule5"; p1 = n;
n = s_new(ident); n->text = "r"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 42; n->pair[1] = 17; p5 = n;
n = s_kid(expr, p5); n->text = "r"; p4 = n;
n = s_new(call); n->text = "Rule5"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "r"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "r"; p5 = n;
n = cons(s_new(ident), p5); n->text = "rep"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_both"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 41; n->pair[1] = 21; p5 = n;
n = s_kid(expr, p5); n->text = " s_both(rep, \"1,\", r) "; p4 = n;
n = cons(s_new(call), p4); n->text = "Plus"; p4 = n;
n = s_new(call); n->text = "Rule5"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "r"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "r"; p5 = n;
n = cons(s_new(ident), p5); n->text = "rep"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_both"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 40; n->pair[1] = 21; p5 = n;
n = s_kid(expr, p5); n->text = " s_both(rep, 0, r) "; p4 = n;
n = cons(s_new(call), p4); n->text = "Star"; p4 = n;
n = s_new(call); n->text = "Rule5"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "r"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "r"; p5 = n;
n = cons(s_new(ident), p5); n->text = "rep"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_both"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 39; n->pair[1] = 22; p5 = n;
n = s_kid(expr, p5); n->text = " s_both(rep, \",1\", r) "; p4 = n;
n = cons(s_new(call), p4); n->text = "Query"; p4 = n;
n = s_new(call); n->text = "Rule5"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "r"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Rule4"; p1 = n;
n = s_new(ident); n->text = "u"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 36; n->pair[1] = 17; p5 = n;
n = s_kid(expr, p5); n->text = "u"; p4 = n;
n = s_new(call); n->text = "Rule4"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "u"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "u"; p5 = n;
n = cons(s_new(ident), p5); n->text = "l"; p5 = n;
n = cons(s_new(ident), p5); n->text = "lit"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_both"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 35; n->pair[1] = 34; p5 = n;
n = s_kid(expr, p5); n->text = " s_both(lit, l, u) "; p4 = n;
n = s_new(call); n->text = "Rule4"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "u"; p4 = n;
n = cons(s_new(call), p4); n->text = "Colon"; p4 = n;
n = s_new(call); n->text = "StringLit"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "l"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "u"; p5 = n;
n = cons(s_new(ident), p5); n->text = "n"; p5 = n;
n = cons(s_new(ident), p5); n->text = "bind"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_both"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 34; n->pair[1] = 29; p5 = n;
n = s_kid(expr, p5); n->text = " s_both(bind, n, u) "; p4 = n;
n = s_new(call); n->text = "Rule4"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "u"; p4 = n;
n = cons(s_new(call), p4); n->text = "Colon"; p4 = n;
n = s_new(call); n->text = "Name"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "n"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "c"; p5 = n;
n = cons(s_new(ident), p5); n->text = "guard"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_retype"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 33; n->pair[1] = 19; p5 = n;
n = s_kid(expr, p5); n->text = " s_retype(guard, c) "; p4 = n;
n = s_new(call); n->text = "Code"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "c"; p4 = n;
n = cons(s_new(call), p4); n->text = "And"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "u"; p5 = n;
n = cons(s_new(ident), p5); n->text = "not"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_kid"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 32; n->pair[1] = 20; p5 = n;
n = s_kid(expr, p5); n->text = " s_kid(not, u) "; p4 = n;
n = s_new(call); n->text = "Rule4"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "u"; p4 = n;
n = cons(s_new(call), p4); n->text = "Not"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "u"; p5 = n;
n = cons(s_new(ident), p5); n->text = "and"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_kid"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 31; n->pair[1] = 20; p5 = n;
n = s_kid(expr, p5); n->text = " s_kid(and, u) "; p4 = n;
n = s_new(call); n->text = "Rule4"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "u"; p4 = n;
n = cons(s_new(call), p4); n->text = "And"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Rule3"; p1 = n;
n = s_new(coords); n->pair[0] = 28; n->pair[1] = 10; p5 = n;
n = s_kid(expr, p5); n->text = " 0 "; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "s"; p5 = n;
n = cons(s_new(ident), p5); n->text = "cafe"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_new"; p5 = n;
n = cons(s_new(ident), p5); n->text = "cons"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 27; n->pair[1] = 23; p5 = n;
n = s_kid(expr, p5); n->text = " cons(s_new(cafe), s) "; p4 = n;
n = s_new(call); n->text = "Rule2"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "s"; p4 = n;
n = cons(s_new(call), p4); n->text = "Dollar"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_new(ident); n->text = "s"; p5 = n;
n = cons(s_new(ident), p5); n->text = "r"; p5 = n;
n = cons(s_new(ident), p5); n->text = "cons"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 26; n->pair[1] = 24; p5 = n;
n = s_kid(expr, p5); n->text = " cons(r, s) "; p4 = n;
n = s_new(call); n->text = "Rule2"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "s"; p4 = n;
n = s_new(call); n->text = "Rule3"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "r"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Rule2"; p1 = n;
n = s_new(ident); n->text = "r"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s"; p5 = n;
n = cons(s_new(ident), p5); n->text = "append"; p5 = n;
n = cons(s_new(ident), p5); n->text = "seq"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_kid"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 23; n->pair[1] = 28; p5 = n;
n = s_kid(expr, p5); n->text = " s_kid(seq, append(s, r)) "; p4 = n;
n = s_new(call); n->text = "Result"; p6 = n;
n = s_kid(rep, p6); n->text = ",1"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "r"; p4 = n;
n = s_new(call); n->text = "Rule2"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "s"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "r"; p5 = n;
n = cons(s_new(ident), p5); n->text = "seq"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_kid"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 22; n->pair[1] = 28; p5 = n;
n = s_kid(expr, p5); n->text = " s_kid(seq, r) "; p4 = n;
n = s_new(call); n->text = "Result"; p6 = n;
n = s_kid(rep, p6); n->text = ",1"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "r"; p4 = n;
n = cons(s_new(call), p4); n->text = "Epsilon"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Rule1"; p1 = n;
n = s_new(ident); n->text = "s"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 19; n->pair[1] = 17; p5 = n;
n = s_kid(expr, p5); n->text = "s"; p4 = n;
n = s_new(call); n->text = "Rule1"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "s"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "r"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s"; p5 = n;
n = cons(s_new(ident), p5); n->text = "s_alt"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 18; n->pair[1] = 30; p5 = n;
n = s_kid(expr, p5); n->text = " s_alt(s, r) "; p4 = n;
n = s_new(call); n->text = "Rule0"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "r"; p4 = n;
n = cons(s_new(call), p4); n->text = "Slash"; p4 = n;
n = s_new(call); n->text = "Rule1"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "s"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Rule0"; p1 = n;
n = s_new(ident); n->text = "r"; p4 = n;
n = cons(s_new(ident), p4); n->text = "t"; p4 = n;
n = cons(s_new(ident), p4); n->text = "type"; p4 = n;
n = cons(s_new(ident), p4); n->text = "s_text"; p4 = n;
n = cons(s_new(ident), p4); n->text = "cons"; p4 = n;
n = cons(s_new(ident), p4); n->text = "n"; p4 = n;
n = cons(s_new(ident), p4); n->text = "rule"; p4 = n;
n = cons(s_new(ident), p4); n->text = "s_both"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 15; n->pair[1] = 3; p4 = n;
n = s_kid(expr, p4); n->text = " s_both(rule, n, cons(s_text(type, t), r)) "; p3 = n;
n = cons(s_new(call), p3); n->text = "_"; p3 = n;
n = s_new(call); n->text = "Rule0"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "r"; p3 = n;
n = cons(s_new(call), p3); n->text = "lArrow"; p3 = n;
n = s_new(call); n->text = "TypeOptional"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "t"; p3 = n;
n = s_new(call); n->text = "Name"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "n"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Defn"; p1 = n;
n = s_new(ident); n->text = "d"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 11; n->pair[1] = 16; p5 = n;
n = s_kid(expr, p5); n->text = "d"; p4 = n;
n = s_new(call); n->text = "Defn"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "d"; p4 = n;
n = s_kid(seq, p4); p3 = n;
n = s_new(ident); n->text = "ds"; p5 = n;
n = cons(s_new(ident), p5); n->text = "d"; p5 = n;
n = cons(s_new(ident), p5); n->text = "cons"; p5 = n;
n = cons(s_new(coords), p5); n->pair[0] = 10; n->pair[1] = 24; p5 = n;
n = s_kid(expr, p5); n->text = " cons(d, ds) "; p4 = n;
n = s_new(call); n->text = "Defns"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "ds"; p4 = n;
n = s_new(call); n->text = "Defn"; p5 = n;
n = cons(s_kid(bind, p5), p4); n->text = "d"; p4 = n;
n = cons(s_kid(seq, p4), p3); p3 = n;
n = s_kid(alt, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Defns"; p1 = n;
n = s_new(ident); n->text = "ds"; p4 = n;
n = cons(s_new(ident), p4); n->text = "p"; p4 = n;
n = cons(s_new(ident), p4); n->text = "cons"; p4 = n;
n = cons(s_new(ident), p4); n->text = "grammar"; p4 = n;
n = cons(s_new(ident), p4); n->text = "s_kid"; p4 = n;
n = cons(s_new(coords), p4); n->pair[0] = 7; n->pair[1] = 6; p4 = n;
n = s_kid(expr, p4); n->text = " s_kid(grammar, cons(p, ds)) "; p3 = n;
n = s_new(call); n->text = "Defns"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "ds"; p3 = n;
n = s_new(call); n->text = "Preamble"; p4 = n;
n = cons(s_kid(bind, p4), p3); n->text = "p"; p3 = n;
n = cons(s_new(call), p3); n->text = "_"; p3 = n;
n = s_kid(seq, p3); p2 = n;
n = cons(s_new(type), p2); n->text = "struct s_node *"; p2 = n;
n = cons(s_kid(rule, p2), p1); n->text = "Grammar"; p1 = n;
n = s_new(ident); n->text = "include"; p2 = n;
n = cons(s_new(coords), p2); n->pair[0] = 1; n->pair[1] = 2; p2 = n;
n = cons(s_kid(preamble, p2), p1); n->text = "\n#include \"syntax.h\"\n"; p1 = n;
n = s_kid(grammar, p1); p0 = n;
*result = p0;
return 1;
}
